# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title A Gibbs sampler using Rcpp
#' @description A Gibbs sampler using Rcpp
#' @param sigma the standard error
#' @param x0 the start point
#' @param N the number of circles
#' @return a numeric matrix of results 
#' @export
rwC_f <- function(sigma, x0, N) {
    .Call('_StatComp20037_rwC_f', PACKAGE = 'StatComp20037', sigma, x0, N)
}

